# -*- coding: utf-8 -*-
#error codes

OK=0				#成功(エラーなし)
NOT_SUPPORTED=1		#サポートされていない呼び出し
FILE_NOT_FOUND=2
PARSING_FAILED=3 #ファイル読み込みエラー
IO_ERROR=4 #ファイル入出力エラー
CANCELED=5#ユーザーによるキャンセル
WAITING_USER=6		#ユーザの操作待ち
FILE_NOT_SUPPORTED=7#対応していないファイル
NOT_AUTHORIZED=8#グーグルで認証していない
NET_ERROR=100#通信関連のエラー
GOOGLE_ERROR = 10
CANCELED_BY_USER = 11
CONNECT_TIMEOUT = 12

STATUS_SOURCE_LOADING = 0x1
STATUS_SOURCE_QUEUED = 0x2
STATUS_SOURCE_EMPTY = 0x4
STATUS_SOURCE_NEEDSTOP = 0x8
STATUS_SOURCE_ERROR = STATUS_SOURCE_NEEDSTOP | 0x10
STATUS_SOURCE_INTERRUPT = STATUS_SOURCE_NEEDSTOP | 0x12
STATUS_ENGINE_FINISHED = 0x1
STATUS_ENGINE_STOPSOURCE = 0x2
STATUS_ENGINE_NEEDSTOP = 0x4
STATUS_ENGINE_INTERRUPT = STATUS_ENGINE_NEEDSTOP | 0x8
STATUS_ENGINE_ERROR = STATUS_ENGINE_NEEDSTOP | 0x10
STATUS_ENGINE_SUCCESS = 0x12
UPDATER_NEED_UPDATE = 200# アップデートが必要
UPDATER_LATEST = 204# アップデートが無い
UPDATER_VISIT_SITE = 205
UPDATER_BAD_PARAM = 400# パラメーターが不正
UPDATER_NOT_FOUND = 404# アプリケーションが存在しない
UNKNOWN=99999
